name: Deployment Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:

  avoid_reduncy:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Redundant Builds
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
  
  check_environment:
    runs-on: ubuntu-latest
    steps:
      - name: Check Environment Variables in PHP code
        uses: actions/checkout@v2
      - name: Install grep
        run: sudo apt-get install grep
      - name: Check for Environment Variables in PHP code
        run: |
          if grep -q '\$_ENV\[' conexion.php; then
            echo "Environment variables found in PHP code."
          else
            echo "No environment variables found in PHP code."
            exit 1
          fi

  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Deploy Login in DigitalOcean
        if: ${{ github.event_name == 'push' }}
        env:
          DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN_LOGIN }}
        run: |
          curl -X POST -H "Content-Type: application/json" -H "Authorization: Bearer $DIGITALOCEAN_TOKEN_LOGIN" https://api.digitalocean.com/v2/apps/$APP_ID/deployments